#table properties
num_players: 9
num_cards: 52
start_credits: 1000
big_blind: 10
small_blind: 5
max_bet: 1.5

#model properties
bins: 9
num_agents: 27
embedding_hidden_dim: 4
feedforward_dim: 12
hidden_size: 16
history_compressor_depth: 25
fold_discount: 0.0025

#train strategy
n_games: 150000
reset_all: True
with_human: False
history_train_freq: 32
brain_train_freq: 10
relocation_freq: 24
checkpoint_freq: 25000
name: "First_long_train"
device: "cuda"
